-- 004_outlet_seed.sql
-- Seeds the `outlets` table with canonical outlet metadata.
-- - `id` comes from the NewsAPI-style source id (e.g. 'abc-news').
-- - Blank boolean fields are treated as false.
-- - api_access and paywall default to 'Pending' when not specified.

BEGIN;

INSERT INTO outlets (
  id,
  name,
  description,
  url,
  category,
  language,
  country,
  list1,
  wh_2022,
  wh_2025,
  list2,
  wire,
  global,
  state_funded,
  list3,
  api_access,
  paywall
) VALUES
  ('abc-news',
   'ABC News',
   'Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.',
   'https://abcnews.go.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('abc-news-au',
   'ABC News (AU)',
   'Australia''s most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.',
   'https://www.abc.net.au/news',
   'general',
   'en',
   'au',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('aftenposten',
   'Aftenposten',
   'Norges ledende nettavis med alltid oppdaterte nyheter innenfor innenriks, utenriks, sport og kultur.',
   'https://www.aftenposten.no',
   'general',
   'no',
   'no',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('al-jazeera-english',
   'Al Jazeera English',
   'News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.',
   'https://www.aljazeera.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('ansa',
   'ANSA.it',
   'Agenzia ANSA: ultime notizie, foto, video e approfondimenti su: cronaca, politica, economia, regioni, mondo, sport, calcio, cultura e tecnologia.',
   'https://www.ansa.it',
   'general',
   'it',
   'it',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('argaam',
   'Argaam',
   'Ø§Ø±Ù‚Ø§Ù… Ù…ÙˆÙ‚Ø¹ Ù…ØªØ®ØµØµ ÙÙŠ Ù…ØªØ§Ø¨Ø¹Ø© Ø³ÙˆÙ‚ Ø§Ù„Ø£Ø³Ù‡Ù… Ø§Ù„Ø³Ø¹ÙˆØ¯ÙŠ ØªØ¯Ø§ÙˆÙ„ - ØªØ§Ø³ÙŠ - Ù…Ø¹ ØªØºØ·ÙŠÙ‡ Ù…Ø¹Ù…Ù‚Ø© Ù„Ø´Ø±ÙƒØ§Øª ÙˆØ§Ø³Ø¹Ø§Ø± ÙˆÙ…Ù†ØªØ¬Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙƒÙŠÙ…Ø§ÙˆÙŠØ§Øª , ØªÙ‚Ø§Ø±ÙŠØ± Ù…Ø§Ù„ÙŠØ© Ø§Ù„Ø§ÙƒØªØªØ§Ø¨Ø§Øª Ø§Ù„Ø¬Ø¯ÙŠØ¯Ù‡',
   'https://www.argaam.com',
   'business',
   'ar',
   'sa',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('ars-technica',
   'Ars Technica',
   'The PC enthusiast''s resource. Power users and the tools they love, without computing religion.',
   'https://arstechnica.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('ary-news',
   'Ary News',
   'ARY News is a Pakistani news channel committed to bring you up-to-the minute Pakistan news and featured stories from around Pakistan and all over the world.',
   'https://arynews.tv/ud/',
   'general',
   'ud',
   'pk',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('associated-press',
   'Associated Press',
   'The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.',
   'https://apnews.com/',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('australian-financial-review',
   'Australian Financial Review',
   'The Australian Financial Review reports the latest news from business, finance, investment and politics, updated in real time. It has a reputation for independent, award-winning journalism and is essential reading for the business and investor community.',
   'http://www.afr.com',
   'business',
   'en',
   'au',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('axios',
   'Axios',
   'Axios are a new media company delivering vital, trustworthy news and analysis in the most efficient, illuminating and shareable ways possible.',
   'https://www.axios.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('bbc-news',
   'BBC News',
   'Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news.',
   'https://www.bbc.co.uk/news',
   'general',
   'en',
   'gb',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('bbc-sport',
   'BBC Sport',
   'The home of BBC Sport online. Includes live sports coverage, breaking news, results, video, audio and analysis on Football, F1, Cricket, Rugby Union, Rugby League, Golf, Tennis and all the main world sports, plus major events such as the Olympic Games.',
   'http://www.bbc.co.uk/sport',
   'sports',
   'en',
   'gb',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('bild',
   'Bild',
   'Die Seite 1 fÃ¼r aktuelle Nachrichten und Themen, Bilder und Videos aus den Bereichen News, Wirtschaft, Politik, Show, Sport, und Promis.',
   'http://www.bild.de',
   'general',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('blasting-news-br',
   'Blasting News (BR)',
   'Descubra a seÃ§Ã£o brasileira da Blasting News, a primeira revista feita pelo pÃºblico, com notÃ­cias globais e vÃ­deos independentes. Junte-se a nÃ³s e torne- se um repÃ³rter.',
   'https://br.blastingnews.com',
   'general',
   'pt',
   'br',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('bleacher-report',
   'Bleacher Report',
   'Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!',
   'http://www.bleacherreport.com',
   'sports',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('bloomberg',
   'Bloomberg',
   'Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.',
   'http://www.bloomberg.com',
   'business',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('breitbart-news',
   'Breitbart News',
   'Syndicated news and opinion website providing continuously updated headlines to top news and analysis sources.',
   'http://www.breitbart.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('business-insider',
   'Business Insider',
   'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.',
   'http://www.businessinsider.com',
   'business',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('buzzfeed',
   'Buzzfeed',
   'BuzzFeed is a cross-platform, global network for news and entertainment that generates seven billion views each month.',
   'https://www.buzzfeed.com',
   'entertainment',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('cbc-news',
   'CBC News',
   'CBC News is the division of the Canadian Broadcasting Corporation responsible for the news gathering and production of news programs on the corporation''s English-language operations, namely CBC Television, CBC Radio, CBC News Network, and CBC.ca.',
   'http://www.cbc.ca/news',
   'general',
   'en',
   'ca',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('cbs-news',
   'CBS News',
   'CBS News: dedicated to providing the best in journalism under standards it pioneered at the dawn of radio and television and continue in the digital age.',
   'http://www.cbsnews.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('cnn',
   'CNN',
   'View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN',
   'http://us.cnn.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('cnn-es',
   'CNN Spanish',
   'Lee las Ãºltimas noticias e informaciÃ³n sobre LatinoamÃ©rica, Estados Unidos, mundo, entretenimiento, polÃ­tica, salud, tecnologÃ­a y deportes en CNNEspaÃ±ol.com.',
   'http://cnnespanol.cnn.com/',
   'general',
   'es',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('crypto-coins-news',
   'Crypto Coins News',
   'Providing breaking cryptocurrency news - focusing on Bitcoin, Ethereum, ICOs, blockchain technology, and smart contracts.',
   'https://www.ccn.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('der-tagesspiegel',
   'Der Tagesspiegel',
   'Nachrichten, News und neueste Meldungen aus dem Inland und dem Ausland - aktuell prÃ¤sentiert von tagesspiegel.de.',
   'http://www.tagesspiegel.de',
   'general',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('die-zeit',
   'Die Zeit',
   'Aktuelle Nachrichten, Kommentare, Analysen und Hintergrundberichte aus Politik, Wirtschaft, Gesellschaft, Wissen, Kultur und Sport lesen Sie auf ZEIT ONLINE.',
   'http://www.zeit.de/index',
   'business',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('el-mundo',
   'El Mundo',
   'Noticias, actualidad, Ã¡lbumes, debates, sociedad, servicios, entretenimiento y Ãºltima hora en EspaÃ±a y el mundo.',
   'http://www.elmundo.es',
   'general',
   'es',
   'es',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('engadget',
   'Engadget',
   'Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics.',
   'https://www.engadget.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('entertainment-weekly',
   'Entertainment Weekly',
   'Online version of the print magazine includes entertainment news, interviews, reviews of music, film, TV and books, and a special area for magazine subscribers.',
   'http://www.ew.com',
   'entertainment',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('espn',
   'ESPN',
   'ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.',
   'https://www.espn.com',
   'sports',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('espn-cric-info',
   'ESPN Cric Info',
   'ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.',
   'http://www.espncricinfo.com/',
   'sports',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('financial-post',
   'Financial Post',
   'Find the latest happenings in the Canadian Financial Sector and stay up to date with changing trends in Business Markets. Read trading and investing advice from professionals.',
   'https://financialpost.com',
   'business',
   'en',
   'ca',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('focus',
   'Focus',
   'Minutenaktuelle Nachrichten und Service-Informationen von Deutschlands modernem Nachrichtenmagazin.',
   'http://www.focus.de',
   'general',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('football-italia',
   'Football Italia',
   'Italian football news, analysis, fixtures and results for the latest from Serie A, Serie B and the Azzurri.',
   'http://www.football-italia.net',
   'sports',
   'en',
   'it',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('fortune',
   'Fortune',
   'Fortune 500 Daily and Breaking Business News',
   'http://fortune.com',
   'business',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('four-four-two',
   'FourFourTwo',
   'The latest football news, in-depth features, tactical and statistical analysis from FourFourTwo, the UK&#039;s favourite football monthly.',
   'http://www.fourfourtwo.com/news',
   'sports',
   'en',
   'gb',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('fox-news',
   'Fox News',
   'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.',
   'http://www.foxnews.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('fox-sports',
   'Fox Sports',
   'Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.',
   'http://www.foxsports.com',
   'sports',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('globo',
   'Globo',
   'SÃ³ na globo.com vocÃª encontra tudo sobre o conteÃºdo e marcas do Grupo Globo. O melhor acervo de vÃ­deos online sobre entretenimento, esportes e jornalismo do Brasil.',
   'http://www.globo.com/',
   'general',
   'pt',
   'br',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('google-news',
   'Google News',
   'Comprehensive, up-to-date news coverage, aggregated from sources all over the world by Google News.',
   'https://news.google.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('goteborgs-posten',
   'GÃ¶teborgs-Posten',
   'GÃ¶teborgs-Posten, abbreviated GP, is a major Swedish language daily newspaper published in Gothenburg, Sweden.',
   'http://www.gp.se',
   'general',
   'sv',
   'se',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('gruenderszene',
   'Gruenderszene',
   'Online-Magazin fÃ¼r Startups und die digitale Wirtschaft. News und HintergrÃ¼nde zu Investment, VC und GrÃ¼ndungen.',
   'http://www.gruenderszene.de',
   'technology',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('hacker-news',
   'Hacker News',
   'Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham''s investment fund and startup incubator, Y Combinator. In general, content that can be submitted is defined as "anything that gratifies one''s intellectual curiosity".',
   'https://news.ycombinator.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('handelsblatt',
   'Handelsblatt',
   'Auf Handelsblatt lesen sie Nachrichten Ã¼ber Unternehmen, Finanzen, Politik und Technik. Verwalten Sie Ihre Finanzanlagen mit Hilfe unserer BÃ¶rsenkurse.',
   'http://www.handelsblatt.com',
   'business',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('ign',
   'IGN',
   'IGN is your site for Xbox One, PS4, PC, Wii-U, Xbox 360, PS3, Wii, 3DS, PS Vita and iPhone games with expert reviews, news, previews, trailers, cheat codes, wiki guides and walkthroughs.',
   'http://www.ign.com',
   'entertainment',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('il-sole-24-ore',
   'Il Sole 24 Ore',
   'Notizie di economia, cronaca italiana ed estera, quotazioni borsa in tempo reale e di finanza, norme e tributi, fondi e obbligazioni, mutui, prestiti e lavoro a cura de Il Sole 24 Ore.',
   'https://www.ilsole24ore.com',
   'business',
   'it',
   'it',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('independent',
   'Independent',
   'National morning quality (tabloid) includes free online access to news and supplements. Insight by Robert Fisk and various other columnists.',
   'http://www.independent.co.uk',
   'general',
   'en',
   'gb',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('infobae',
   'Infobae',
   'Noticias de Argentina y del mundo en tiempo real. InformaciÃ³n, videos y fotos sobre los hechos mÃ¡s relevantes y sus protagonistas. LÃ©elo antes en infobae.',
   'http://www.infobae.com/?noredirect',
   'general',
   'es',
   'ar',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('info-money',
   'InfoMoney',
   'No InfoMoney vocÃª encontra tudo o que precisa sobre dinheiro. AÃ§Ãµes, investimentos, bolsas de valores e muito mais. Aqui vocÃª encontra informaÃ§Ã£o que vale dinheiro!',
   'https://www.infomoney.com.br',
   'business',
   'pt',
   'br',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('la-gaceta',
   'La Gaceta',
   'El diario de TucumÃ¡n, noticias 24 horas online - San Miguel de TucumÃ¡n - Argentina - Ultimo momento - Ultimas noticias.',
   'http://www.lagaceta.com.ar',
   'general',
   'es',
   'ar',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('la-nacion',
   'La Nacion',
   'InformaciÃ³n confiable en Internet. Noticias de Argentina y del mundo - Â¡Informate ya!',
   'http://www.lanacion.com.ar',
   'general',
   'es',
   'ar',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('la-repubblica',
   'La Repubblica',
   'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.',
   'http://www.repubblica.it',
   'general',
   'it',
   'it',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('le-monde',
   'Le Monde',
   'Les articles du journal et toute l''actualitÃ© en continu : International, France, SociÃ©tÃ©, Economie, Culture, Environnement, Blogs ...',
   'http://www.lemonde.fr',
   'general',
   'fr',
   'fr',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('lenta',
   'Lenta',
   'ÐÐ¾Ð²Ð¾ÑÑ‚Ð¸, ÑÑ‚Ð°Ñ‚ÑŒÐ¸, Ñ„Ð¾Ñ‚Ð¾Ð³Ñ€Ð°Ñ„Ð¸Ð¸, Ð²Ð¸Ð´ÐµÐ¾. Ð¡ÐµÐ¼ÑŒ Ð´Ð½ÐµÐ¹ Ð² Ð½ÐµÐ´ÐµÐ»ÑŽ, 24 Ñ‡Ð°ÑÐ° Ð² ÑÑƒÑ‚ÐºÐ¸.',
   'https://lenta.ru',
   'general',
   'ru',
   'ru',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('lequipe',
   'L''equipe',
   'Le sport en direct sur L''EQUIPE.fr. Les informations, rÃ©sultats et classements de tous les sports. Directs commentÃ©s, images et vidÃ©os Ã regarder et Ã partager !',
   'https://www.lequipe.fr',
   'sports',
   'fr',
   'fr',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('les-echos',
   'Les Echos',
   'Toute l''actualitÃ© Ã©conomique, financiÃ¨re et boursiÃ¨re franÃ§aise et internationale sur Les Echos.fr',
   'https://www.lesechos.fr',
   'business',
   'fr',
   'fr',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('liberation',
   'LibÃ©ration',
   'Toute l''actualitÃ© en direct - photos et vidÃ©os avec LibÃ©ration',
   'http://www.liberation.fr',
   'general',
   'fr',
   'fr',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('marca',
   'Marca',
   'La mejor informaciÃ³n deportiva en castellano actualizada minuto a minuto en noticias, vÃ­deos, fotos, retransmisiones y resultados en directo.',
   'http://www.marca.com',
   'sports',
   'es',
   'es',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('mashable',
   'Mashable',
   'Mashable is a global, multi-platform media and entertainment company.',
   'https://mashable.com',
   'entertainment',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('medical-news-today',
   'Medical News Today',
   'Medical news and health news headlines posted throughout the day, every day.',
   'http://www.medicalnewstoday.com',
   'health',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('msnbc',
   'MS Now',
   'Breaking news and in-depth analysis of the headlines, as well as commentary and informed perspectives from The Rachel Maddow Show, Morning Joe & more.',
   'http://www.ms.now',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('mtv-news',
   'MTV News',
   'The ultimate news source for music, celebrity, entertainment, movies, and current events on the web. It''s pop culture on steroids.',
   'http://www.mtv.com/news',
   'entertainment',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('mtv-news-uk',
   'MTV News (UK)',
   'All the latest celebrity news, gossip, exclusive interviews and pictures from the world of music and entertainment.',
   'http://www.mtv.co.uk/news',
   'entertainment',
   'en',
   'gb',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('national-geographic',
   'National Geographic',
   'Reporting our world daily: original nature and science news from National Geographic.',
   'http://news.nationalgeographic.com',
   'science',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('national-review',
   'National Review',
   'National Review: Conservative News, Opinion, Politics, Policy, & Current Events.',
   'https://www.nationalreview.com/',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('nbc-news',
   'NBC News',
   'Breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.',
   'http://www.nbcnews.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('news24',
   'News24',
   'South Africa''s premier news source, provides breaking news on national, world, Africa, sport, entertainment, technology and more.',
   'http://www.news24.com',
   'general',
   'en',
   'za',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('new-scientist',
   'New Scientist',
   'Breaking science and technology news from around the world. Exclusive stories and expert analysis on space, technology, health, physics, life and Earth.',
   'https://www.newscientist.com/section/news',
   'science',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('news-com-au',
   'News.com.au',
   'We say what people are thinking and cover the issues that get people talking balancing Australian and global moments â€” from politics to pop culture.',
   'http://www.news.com.au',
   'general',
   'en',
   'au',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('newsweek',
   'Newsweek',
   'Newsweek provides in-depth analysis, news and opinion about international issues, technology, business, culture and politics.',
   'https://www.newsweek.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('new-york-magazine',
   'New York Magazine',
   'NYMAG and New York magazine cover the new, the undiscovered, the next in politics, culture, food, fashion, and behavior nationally, through a New York lens.',
   'https://nymag.com/',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('next-big-future',
   'Next Big Future',
   'Coverage of science and technology that have the potential for disruption, and analysis of plans, policies, and technology that enable radical improvement.',
   'https://www.nextbigfuture.com',
   'science',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('nfl-news',
   'NFL News',
   'The official source for NFL news, schedules, stats, scores and more.',
   'https://www.nfl.com',
   'sports',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('nhl-news',
   'NHL News',
   'The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.',
   'https://www.nhl.com/news',
   'sports',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('nrk',
   'NRK',
   'NRK er Norges stÃ¸rste tilbud pÃ¥ nett: nyheter fra Norge og verden, lokalnyheter, radio- og tv-program, podcast, vÃ¦r, helse-, kultur-, underholdning-, humor- og debattstoff.',
   'https://www.nrk.no',
   'general',
   'no',
   'no',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('politico',
   'Politico',
   'Political news about Congress, the White House, campaigns, lobbyists and issues.',
   'https://www.politico.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('polygon',
   'Polygon',
   'Polygon is a gaming website in partnership with Vox Media. Our culture focused site covers games, their creators, the fans, trending stories and entertainment news.',
   'http://www.polygon.com',
   'entertainment',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('rbc',
   'RBC',
   'Ð“Ð»Ð°Ð²Ð½Ñ‹Ðµ Ð½Ð¾Ð²Ð¾ÑÑ‚Ð¸ Ð¿Ð¾Ð»Ð¸Ñ‚Ð¸ÐºÐ¸, ÑÐºÐ¾Ð½Ð¾Ð¼Ð¸ÐºÐ¸ Ð¸ Ð±Ð¸Ð·Ð½ÐµÑÐ°, ÐºÐ¾Ð¼Ð¼ÐµÐ½Ñ‚Ð°Ñ€Ð¸Ð¸ Ð°Ð½Ð°Ð»Ð¸Ñ‚Ð¸ÐºÐ¾Ð², Ñ„Ð¸Ð½Ð°Ð½ÑÐ¾Ð²Ñ‹Ðµ Ð´Ð°Ð½Ð½Ñ‹Ðµ Ñ Ñ€Ð¾ÑÑÐ¸Ð¹ÑÐºÐ¸Ñ… Ð¸ Ð¼Ð¸Ñ€Ð¾Ð²Ñ‹Ñ… Ð±Ð¸Ñ€Ð¶ÐµÐ²Ñ‹Ñ… ÑÐ¸ÑÑ‚ÐµÐ¼ Ð½Ð° ÑÐ°Ð¹Ñ‚Ðµ rbc.ru.',
   'https://www.rbc.ru',
   'general',
   'ru',
   'ru',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('recode',
   'Recode',
   'Get the latest independent tech news, reviews and analysis from Recode with the most informed and respected journalists in technology and media.',
   'http://www.recode.net',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('reddit-r-all',
   'Reddit /r/all',
   'Reddit is an entertainment, social news networking service, and news website. Reddit''s registered community members can submit content, such as text posts or direct links.',
   'https://www.reddit.com/r/all',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('rt',
   'RT',
   'ÐÐºÑ‚ÑƒÐ°Ð»ÑŒÐ½Ð°Ñ ÐºÐ°Ñ€Ñ‚Ð¸Ð½Ð° Ð´Ð½Ñ Ð½Ð° RT: ÐºÑ€ÑƒÐ³Ð»Ð¾ÑÑƒÑ‚Ð¾Ñ‡Ð½Ð¾Ðµ ÐµÐ¶ÐµÐ´Ð½ÐµÐ²Ð½Ð¾Ðµ Ð¾Ð±Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ Ð½Ð¾Ð²Ð¾ÑÑ‚ÐµÐ¹ Ð¿Ð¾Ð»Ð¸Ñ‚Ð¸ÐºÐ¸, Ð±Ð¸Ð·Ð½ÐµÑÐ°, Ñ„Ð¸Ð½Ð°Ð½ÑÐ¾Ð², ÑÐ¿Ð¾Ñ€Ñ‚Ð°, Ð½Ð°ÑƒÐºÐ¸, ÐºÑƒÐ»ÑŒÑ‚ÑƒÑ€Ñ‹. ÐžÐ½Ð»Ð°Ð¹Ð½-Ñ€ÐµÐ¿Ð¾Ñ€Ñ‚Ð°Ð¶Ð¸ Ñ Ð¼ÐµÑÑ‚Ð° ÑÐ¾Ð±Ñ‹Ñ‚Ð¸Ð¹. ÐšÐ¾Ð¼Ð¼ÐµÐ½Ñ‚Ð°Ñ€Ð¸Ð¸ ÑÐºÑÐ¿ÐµÑ€Ñ‚Ð¾Ð², Ð°ÐºÑ‚ÑƒÐ°Ð»ÑŒÐ½Ñ‹Ðµ Ð¸Ð½Ñ‚ÐµÑ€Ð²ÑŒÑŽ, Ñ„Ð¾Ñ‚Ð¾ Ð¸ Ð²Ð¸Ð´ÐµÐ¾ Ñ€ÐµÐ¿Ð¾Ñ€Ñ‚Ð°Ð¶Ð¸.',
   'https://russian.rt.com',
   'general',
   'ru',
   'ru',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('rte',
   'RTE',
   'Get all of the latest breaking local and international news stories as they happen, with up to the minute updates and analysis, from Ireland''s National Broadcaster.',
   'https://www.rte.ie/news',
   'general',
   'en',
   'ie',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('rtl-nieuws',
   'RTL Nieuws',
   'Volg het nieuws terwijl het gebeurt. RTL Nieuws informeert haar lezers op een onafhankelijke, boeiende en toegankelijke wijze over belangrijke ontwikkelingen in eigen land en de rest van de wereld.',
   'https://www.rtlnieuws.nl/',
   'general',
   'nl',
   'nl',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('sabq',
   'SABQ',
   'ØµØ­ÙŠÙØ© Ø§Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ø³Ø¹ÙˆØ¯ÙŠØ© Ù‡Ø¯ÙÙ‡Ø§ Ø§Ù„Ø³Ø¨Ù‚ ÙÙŠ Ù†Ù‚Ù„ Ø§Ù„Ø­Ø¯Ø« Ø¨Ù…Ù‡Ù†ÙŠØ© ÙˆÙ…ØµØ¯Ø§Ù‚ÙŠØ© Ø®Ø¯Ù…Ø© Ù„Ù„ÙˆØ·Ù† ÙˆØ§Ù„Ù…ÙˆØ§Ø·Ù†.',
   'https://sabq.org',
   'general',
   'ar',
   'sa',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('spiegel-online',
   'Spiegel Online',
   'Deutschlands fÃ¼hrende Nachrichtenseite. Alles Wichtige aus Politik, Wirtschaft, Sport, Kultur, Wissenschaft, Technik und mehr.',
   'http://www.spiegel.de',
   'general',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('svenska-dagbladet',
   'Svenska Dagbladet',
   'Sveriges ledande mediesajt - SvD.se. Svenska Dagbladets nyhetssajt lÃ¥ter lÃ¤sarna ta plats und fÃ¶rdjupar nyheterna.',
   'https://www.svd.se',
   'general',
   'sv',
   'se',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('t3n',
   'T3n',
   'Das Online-Magazin bietet Artikel zu den Themen E-Business, Social Media, Startups und Webdesign.',
   'https://t3n.de',
   'technology',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('talksport',
   'TalkSport',
   'Tune in to the world''s biggest sports radio station - Live Premier League football coverage, breaking sports news, transfer rumours &amp; exclusive interviews.',
   'http://talksport.com',
   'sports',
   'en',
   'gb',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('techcrunch',
   'TechCrunch',
   'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.',
   'https://techcrunch.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('techcrunch-cn',
   'TechCrunch (CN)',
   'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.',
   'https://techcrunch.cn',
   'technology',
   'zh',
   'zh',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('techradar',
   'TechRadar',
   'The latest technology news and reviews, covering computing, home entertainment systems, gadgets and more.',
   'https://www.techradar.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-american-conservative',
   'The American Conservative',
   'Realism and reform. A new voice for a new generation of conservatives.',
   'http://www.theamericanconservative.com/',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-globe-and-mail',
   'The Globe And Mail',
   'The Globe and Mail offers the most authoritative news in Canada, featuring national and international news.',
   'https://www.theglobeandmail.com',
   'general',
   'en',
   'ca',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-hill',
   'The Hill',
   'The Hill is a top US political website, read by the White House and more lawmakers than any other site -- vital for policy, politics and election campaigns.',
   'https://thehill.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-hindu',
   'The Hindu',
   'The Hindu. latest news, analysis, comment, in-depth coverage of politics, business, sport, environment, cinema and arts from India''s national newspaper.',
   'http://www.thehindu.com',
   'general',
   'en',
   'in',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-huffington-post',
   'The Huffington Post',
   'The Huffington Post is a politically liberal American online news aggregator and blog that has both localized and international editions founded by Arianna Huffington, Kenneth Lerer, Andrew Breitbart, and Jonah Peretti, featuring columnists.',
   'http://www.huffingtonpost.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-irish-times',
   'The Irish Times',
   'The Irish Times online. Latest news including sport, analysis, business, weather and more from the definitive brand of quality news in Ireland.',
   'https://www.irishtimes.com',
   'general',
   'en',
   'ie',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-jerusalem-post',
   'The Jerusalem Post',
   'The Jerusalem Post is the leading online newspaper for English speaking Jewry since 1932, bringing news and updates from the Middle East and all over the Jewish world.',
   'https://www.jpost.com/',
   'general',
   'en',
   'is',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-lad-bible',
   'The Lad Bible',
   'The LAD Bible is one of the largest community for guys aged 16-30 in the world. Send us your funniest pictures and videos!',
   'https://www.theladbible.com',
   'entertainment',
   'en',
   'gb',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-next-web',
   'The Next Web',
   'The Next Web is one of the worldâ€™s largest online publications that delivers an international perspective on the latest news about Internet technology, business and culture.',
   'http://thenextweb.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-sport-bible',
   'The Sport Bible',
   'TheSPORTbible is one of the largest communities for sports fans across the world. Send us your sporting pictures and videos!',
   'https://www.thesportbible.com',
   'sports',
   'en',
   'gb',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-times-of-india',
   'The Times of India',
   'Times of India brings the Latest News and Top Breaking headlines on Politics and Current Affairs in India and around the World, Sports, Business, Bollywood News and Entertainment, Science, Technology, Health and Fitness news, Cricket and opinions from leading columnists.',
   'http://timesofindia.indiatimes.com',
   'general',
   'en',
   'in',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-verge',
   'The Verge',
   'The Verge covers the intersection of technology, science, art, and culture.',
   'http://www.theverge.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-wall-street-journal',
   'The Wall Street Journal',
   'WSJ online coverage of breaking news and current headlines from the US and around the world. Top stories, photos, videos, detailed analysis and in-depth reporting.',
   'https://www.wsj.com',
   'business',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-washington-post',
   'The Washington Post',
   'Breaking news and analysis on politics, business, world national news, entertainment more. In-depth DC, Virginia, Maryland news coverage including traffic, weather, crime, education, restaurant reviews and more.',
   'https://www.washingtonpost.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('the-washington-times',
   'The Washington Times',
   'The Washington Times delivers breaking news and commentary on the issues that affect the future of our nation.',
   'https://www.washingtontimes.com/',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('time',
   'Time',
   'Breaking news and analysis from TIME.com. Politics, world news, photos, video, tech reviews, health, science and entertainment news.',
   'http://time.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('usa-today',
   'USA Today',
   'Get the latest national, international, and political news at USATODAY.com.',
   'http://www.usatoday.com/news',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('vice-news',
   'Vice News',
   'Vice News is Vice Media, Inc.''s current affairs channel, producing daily documentary essays and video through its website and YouTube channel. It promotes itself on its coverage of "under - reported stories".',
   'https://news.vice.com',
   'general',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('wired',
   'Wired',
   'Wired is a monthly American magazine, published in print and online editions, that focuses on how emerging technologies affect culture, the economy, and politics.',
   'https://www.wired.com',
   'technology',
   'en',
   'us',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('wired-de',
   'Wired.de',
   'Wired reports on how emerging technologies affect culture, the economy and politics.',
   'https://www.wired.de',
   'technology',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('wirtschafts-woche',
   'Wirtschafts Woche',
   'Das Online-Portal des fÃ¼hrenden Wirtschaftsmagazins in Deutschland. Das Entscheidende zu Unternehmen, Finanzen, Erfolg und Technik.',
   'http://www.wiwo.de',
   'business',
   'de',
   'de',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('xinhua-net',
   'Xinhua Net',
   'ä¸­å›½ä¸»è¦é‡ç‚¹æ–°é—»ç½‘ç«™,ä¾æ‰˜æ–°åŽç¤¾éå¸ƒå…¨çƒçš„é‡‡ç¼–ç½‘ç»œ,è®°è€…éå¸ƒä¸–ç•Œ100å¤šä¸ªå›½å®¶å’Œåœ°åŒº,åœ°æ–¹é¢‘é“åˆ†å¸ƒå…¨å›½31ä¸ªçœå¸‚è‡ªæ²»åŒº,æ¯å¤©24å°æ—¶åŒæ—¶ä½¿ç”¨6ç§è¯­è¨€æ»šåŠ¨å‘ç¨¿,æƒå¨ã€å‡†ç¡®ã€åŠæ—¶æ’­å‘å›½å†…å¤–é‡è¦æ–°é—»å’Œé‡å¤§çªå‘äº‹ä»¶,å—ä¼—è¦†ç›–200å¤šä¸ªå›½å®¶å’Œåœ°åŒº,å‘å±•è®ºå›æ˜¯å…¨çƒçŸ¥åçš„ä¸­æ–‡è®ºå›ã€‚',
   'http://xinhuanet.com/',
   'general',
   'zh',
   'zh',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending'),
  ('ynet',
   'Ynet',
   'ynet ×“×£ ×”×‘×™×ª: ××ª×¨ ×”×—×“×©×•×ª ×”×ž×•×‘×™×œ ×‘×™×©×¨××œ ×ž×‘×™×ª ×™×“×™×¢×•×ª ××—×¨×•× ×•×ª. ×¡×™×§×•×¨ ×ž×œ× ×©×œ ×—×“×©×•×ª ×ž×™×©×¨××œ ×•×”×¢×•×œ×, ×¡×¤×•×¨×˜, ×›×œ×›×œ×”, ×ª×¨×‘×•×ª, ××•×›×œ, ×ž×“×¢ ×•×˜×‘×¢, ×›×œ ×ž×” ×©×§×•×¨×” ×•×›×œ ×ž×” ×©×ž×¢× ×™×™×Ÿ ×‘ ynet.',
   'http://www.ynet.co.il',
   'general',
   'he',
   'is',
   false, false, false, false, false, false, false, false,
   'Pending', 'Pending')
ON CONFLICT (id) DO UPDATE SET
  name         = EXCLUDED.name,
  description  = EXCLUDED.description,
  url          = EXCLUDED.url,
  category     = EXCLUDED.category,
  language     = EXCLUDED.language,
  country      = EXCLUDED.country,
  list1        = EXCLUDED.list1,
  wh_2022      = EXCLUDED.wh_2022,
  wh_2025      = EXCLUDED.wh_2025,
  list2        = EXCLUDED.list2,
  wire         = EXCLUDED.wire,
  global       = EXCLUDED.global,
  state_funded = EXCLUDED.state_funded,
  list3        = EXCLUDED.list3,
  api_access   = EXCLUDED.api_access,
  paywall      = EXCLUDED.paywall;

COMMIT;
